In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('titanic/Titanic-Dataset.csv')

In [3]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
df['family_size'] = df['SibSp'] + df['Parch'] + 1

In [7]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,family_size
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,2
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,2
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,1
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,2
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,1

In [8]:
df = pd.get_dummies(df, columns=['Sex', 'Embarked'], drop_first=True)

In [9]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,family_size,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,2,True,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,2,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,2,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,1,True,False,True

In [32]:
X.loc[:, 'Age'] = X['Age'].fillna(X['Age'].median())

In [33]:
print(X.isnull().sum())

Pclass         0
Age            0
Fare           0
family_size    0
Sex_male       0
Embarked_Q     0
Embarked_S     0
dtype: int64

In [37]:
df['Age'] = df['Age'].fillna(df['Age'].median())

In [38]:
X = df[['Pclass', 'Age', 'Fare', 'family_size', 'Sex_male', 'Embarked_Q', 'Embarked_S']]
y = df['Survived']

In [39]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,family_size,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,2,True,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,2,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,2,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,1,True,False,True

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [42]:
print("Training test size: ", X_train.shape)
print("Test set size: ", X_test.shape)

Training test size:  (712, 7)
Test set size:  (179, 7)

In [43]:
from sklearn.linear_model import LogisticRegression

In [44]:
model = LogisticRegression(max_iter=1000)

In [45]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [46]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
family_size      0
Sex_male         0
Embarked_Q       0
Embarked_S       0
dtype: int64

In [47]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [52]:
y_pred = model.predict(X_test)

In [54]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.8044692737430168
Confusion Matrix:
 [[90 15]
 [20 54]]
Classification Report:
               precision    recall  f1-score   support

           0       0.82      0.86      0.84       105
           1       0.78      0.73      0.76        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.80       179
weighted avg       0.80      0.80      0.80       179

In [55]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,family_size,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,2,True,False,True
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,2,False,False,False
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,False,False,True
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,2,False,False,True
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,1,True,False,True

In [57]:
df_sorted = df.sort_values(by='Age', ascending=False)

In [59]:
df_sorted.tail()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,family_size,Sex_male,Embarked_Q,Embarked_S
831,832,1,2,"Richards, Master. George Sibley",0.83,1,1,29106,18.7500,NaN,3,True,False,True
469,470,1,3,"Baclini, Miss. Helene Barbara",0.75,2,1,2666,19.2583,NaN,4,False,False,False
644,645,1,3,"Baclini, Miss. Eugenie",0.75,2,1,2666,19.2583,NaN,4,False,False,False
755,756,1,2,"Hamalainen, Master. Viljo",0.67,1,1,250649,14.5000,NaN,3,True,False,True
803,804,1,3,"Thomas, Master. Assad Alexander",0.42,0,1,2625,8.5167,NaN,2,True,False,False

In [63]:
print(df['Age'].dtype)

float64

In [68]:
non_numeric = df[~df['Age'].apply(lambda x: isinstance(x, (int, float)))]
print(non_numeric['Age'].unique())

[]

In [69]:
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
print(df['Age'].isnull().sum())

0

In [70]:
df['AgeBin'] = pd.cut(df['Age'], bins=[0, 12, 20, 40, 60, 80], labels=['Child', 'Teen', 'Adult', 'Middle-aged', 'Senior'])

In [71]:
df['Pclass_fare'] = df['Pclass'] * df['Fare']
df['Family_size_Pclass'] = df['family_size'] * df['Pclass_fare']

print(df[['Pclass', 'Fare', 'Pclass_fare', 'Family_size_Pclass']])

     Pclass     Fare  Pclass_fare  Family_size_Pclass
0         3   7.2500      21.7500             43.5000
1         1  71.2833      71.2833            142.5666
2         3   7.9250      23.7750             23.7750
3         1  53.1000      53.1000            106.2000
4         3   8.0500      24.1500             24.1500
..      ...      ...          ...                 ...
886       2  13.0000      26.0000             26.0000
887       1  30.0000      30.0000             30.0000
888       3  23.4500      70.3500            281.4000
889       1  30.0000      30.0000             30.0000
890       3   7.7500      23.2500             23.2500

[891 rows x 4 columns]

In [73]:
X = df[['Pclass', 'Age', 'Fare', 'family_size', 'Sex_male', 'Embarked_Q', 'Embarked_S', 'Pclass_fare', 'Family_size_Pclass']]
y = df['Survived']

In [74]:
df.isnull().sum()

PassengerId             0
Survived                0
Pclass                  0
Name                    0
Age                     0
SibSp                   0
Parch                   0
Ticket                  0
Fare                    0
Cabin                 687
family_size             0
Sex_male                0
Embarked_Q              0
Embarked_S              0
AgeBin                  0
Pclass_fare             0
Family_size_Pclass      0
dtype: int64

In [75]:
X_train, X_test , y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [76]:
model = LogisticRegression(max_iter=1000)

In [77]:
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [78]:
y_pred = model.predict(X_test)

In [79]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

Accuracy: 0.7988826815642458
Confusion Matrix:
 [[90 15]
 [21 53]]
Classification Report:
               precision    recall  f1-score   support

           0       0.81      0.86      0.83       105
           1       0.78      0.72      0.75        74

    accuracy                           0.80       179
   macro avg       0.80      0.79      0.79       179
weighted avg       0.80      0.80      0.80       179

In [80]:
df.head()

,PassengerId,Survived,Pclass,Name,Age,SibSp,Parch,Ticket,Fare,Cabin,family_size,Sex_male,Embarked_Q,Embarked_S,AgeBin,Pclass_fare,Family_size_Pclass
0,1,0,3,"Braund, Mr. Owen Harris",22.0,1,0,A/5 21171,7.2500,NaN,2,True,False,True,Adult,21.7500,43.5000
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,1,0,PC 17599,71.2833,C85,2,False,False,False,Adult,71.2833,142.5666
2,3,1,3,"Heikkinen, Miss. Laina",26.0,0,0,STON/O2. 3101282,7.9250,NaN,1,False,False,True,Adult,23.7750,23.7750
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,1,0,113803,53.1000,C123,2,False,False,True,Adult,53.1000,106.2000
4,5,0,3,"Allen, Mr. William Henry",35.0,0,0,373450,8.0500,NaN,1,True,False,True,Adult,24.1500,24.1500